improve error reporting

diff --git a/bench-wrap b/bench-wrap
--- a/bench-wrap
+++ b/bench-wrap
@@ -1,6 +1,11 @@
 #!/bin/bash
 
-set -eu
+set -eEu
+catch() {
+    echo "Error $1 occurred on line $2 in $0" >> $GLOBALDIR/error
+}
+trap 'catch $? $LINENO' ERR
+
 
 if [ $# -lt 4 ]
 then
